/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelcraftRouteImport } from './routes/panelcraft'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiOcrScriptRouteImport } from './routes/api/ocr-script'
import { Route as ApiOcrBalloonRouteImport } from './routes/api/ocr-balloon'

const PanelcraftRoute = PanelcraftRouteImport.update({
  id: '/panelcraft',
  path: '/panelcraft',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiOcrScriptRoute = ApiOcrScriptRouteImport.update({
  id: '/api/ocr-script',
  path: '/api/ocr-script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOcrBalloonRoute = ApiOcrBalloonRouteImport.update({
  id: '/api/ocr-balloon',
  path: '/api/ocr-balloon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/panelcraft': typeof PanelcraftRoute
  '/api/ocr-balloon': typeof ApiOcrBalloonRoute
  '/api/ocr-script': typeof ApiOcrScriptRoute
}
export interface FileRoutesByTo {
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/panelcraft': typeof PanelcraftRoute
  '/api/ocr-balloon': typeof ApiOcrBalloonRoute
  '/api/ocr-script': typeof ApiOcrScriptRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/panelcraft': typeof PanelcraftRoute
  '/api/ocr-balloon': typeof ApiOcrBalloonRoute
  '/api/ocr-script': typeof ApiOcrScriptRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/panelcraft'
    | '/api/ocr-balloon'
    | '/api/ocr-script'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/diagnostics'
    | '/login'
    | '/panelcraft'
    | '/api/ocr-balloon'
    | '/api/ocr-script'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/diagnostics'
    | '/login'
    | '/panelcraft'
    | '/api/ocr-balloon'
    | '/api/ocr-script'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DiagnosticsRoute: typeof DiagnosticsRoute
  LoginRoute: typeof LoginRoute
  PanelcraftRoute: typeof PanelcraftRoute
  ApiOcrBalloonRoute: typeof ApiOcrBalloonRoute
  ApiOcrScriptRoute: typeof ApiOcrScriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panelcraft': {
      id: '/panelcraft'
      path: '/panelcraft'
      fullPath: '/panelcraft'
      preLoaderRoute: typeof PanelcraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/ocr-script': {
      id: '/api/ocr-script'
      path: '/api/ocr-script'
      fullPath: '/api/ocr-script'
      preLoaderRoute: typeof ApiOcrScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocr-balloon': {
      id: '/api/ocr-balloon'
      path: '/api/ocr-balloon'
      fullPath: '/api/ocr-balloon'
      preLoaderRoute: typeof ApiOcrBalloonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DiagnosticsRoute: DiagnosticsRoute,
  LoginRoute: LoginRoute,
  PanelcraftRoute: PanelcraftRoute,
  ApiOcrBalloonRoute: ApiOcrBalloonRoute,
  ApiOcrScriptRoute: ApiOcrScriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
